### ISSUE TITLE
can we add graphs?

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#59]
I don't know if we really need this but it would be awesome to have them.

**Comment by baljinderxd** [comment]
Hey @gurrrung , we can send graphs using quickchart.io. In this we just have to send data in form of link in telegram send photo method. Telegram will automatically fetch and send it as photo. I will try and show the result in a day or two if you can specify me in what commands we need to send graphs.

**Comment by gurrrung** [comment]
Great, we can give it a try.

**Comment by gurrrung** [comment]
First of all, we can try graph of `daily` command.
`g daily` should give the bar chart form of the data of the daily command.

**Comment by baljinderxd** [comment]
> `g daily` should give the bar chart form of the data of the daily command.

okay i will implement this in a day or two😋

**Comment by baljinderxd** [comment]
here, I implemented graph as you said.
we can change the color of bars etc and other things too 
![daily graph](https://user-images.githubusercontent.com/57032785/90379822-dddb2980-e098-11ea-9af6-7188e404ac83.png)

**Comment by gurrrung** [comment]
that's great, let's do a PR.
We have to make sure colors works well in dark mode too.

**Comment by baljinderxd** [comment]
> that's great, let's do a PR.

okay making a PR now

> We have to make sure colors works well in dark mode too.

yes sure😀
