### ISSUE TITLE
update new image in readme

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#60]
Add android screenshots

**Comment by vj-abishek** [comment]
Can I do this?

**Comment by gurrrung** [comment]
> Can I do this?

Yes, please.

**Comment by vj-abishek** [comment]
Where are the screenshots?

**Comment by vj-abishek** [comment]
Can you please explain, what to do exactly !!

**Comment by gurrrung** [comment]
Just visit the Telegram Bot in your Android phone, take a screenshot of
graph, delhi and daily command and add in the README.

**Comment by vj-abishek** [comment]
These images are okay?

![7e62f1af-57d4-48cf-a53e-2a6b445c5ae3](https://user-images.githubusercontent.com/43115551/94915634-dba72000-04ca-11eb-8d3a-920fc442b4f6.jpg)
![309b0560-ab14-4f9e-a043-49f182791995](https://user-images.githubusercontent.com/43115551/94915637-dcd84d00-04ca-11eb-9474-9a74919b77b9.jpg)

**Comment by vj-abishek** [comment]
Need to add any other image?

**Comment by vj-abishek** [comment]
![264a8a1f-e75e-43db-bbed-a7690d7657f6](https://user-images.githubusercontent.com/43115551/94989552-5b98bd00-0593-11eb-8365-ca4f56e0a837.jpg)
![f70c00e7-c80d-4572-b25d-49ed330609e1](https://user-images.githubusercontent.com/43115551/94989554-5d628080-0593-11eb-8264-b2ab58ada6ca.jpg)
![22c05262-c2b7-40d8-a496-62d540fab417](https://user-images.githubusercontent.com/43115551/94989555-5e93ad80-0593-11eb-8e01-80f89a43bf45.jpg)

**Comment by vj-abishek** [comment]
@gurrrung Done. Here is the PR #92
