### ISSUE TITLE
delete the graph image after 5 minutes to save user's space

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#67]
Research to be done on how to make this possible.

**Comment by baljinderxd** [comment]
I searched about this and was not able to find anything where bot itself can delete the message after a period of time.

What now I have done is that I have implemented an inline keyboard with the graph images with a delete button. And tapping the button deletes the graph image from the chat and device too thus saving the user's space.

![image](https://user-images.githubusercontent.com/57032785/93460437-d78ed600-f900-11ea-8910-732ae708c744.png)


So if you want I can make a PR for what I have implemented.

**Comment by baljinderxd** [comment]
Mine take on this is similar to yours. Graph images are very small in size and can be deleted by the user themselves anytime. 
You may proceed to close this issue. 👍
