### ISSUE TITLE
add titles to the charts

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#79]
A title would be great as the description of respective commands in the README.

**Comment by baljinderxd** [comment]
I implemented it in two ways. One is using the title in the graph itself and the other is using a caption under the photo.
The title reduces the height of the plotted graph.
Have a look and do tell which one should I implement
![image](https://user-images.githubusercontent.com/57032785/91706022-6aa6dc80-eb9b-11ea-92c8-d9ae32375165.png)

**Comment by gurrrung** [comment]
We can go with the first one because it looks more intuitive to me, what do you think?

**Comment by baljinderxd** [comment]
Going with the first one as it is better to have all the information in the graph itself.
