### ISSUE TITLE
use the URL shortner

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#81]
Make sure `graph 180` works.

**Comment by gurrrung** [comment]
@baljinderxd would you like to give it a try?

**Comment by baljinderxd** [comment]
> @baljinderxd would you like to give it a try?

Yes sure. Will try and make a PR by end of the day tomorrow.😬

**Comment by gurrrung** [comment]
> Yes sure. Will try and make a PR by end of the day tomorrow.
Great, we will need to add this for all graph commands later but for now `graph` command is the only priority.

**Comment by gurrrung** [comment]
Till then I'm restricting the `graph N` command to a smaller value of N to prevent crashes.

**Comment by baljinderxd** [comment]
>`graph` command is the only priority.

Okay then, I will implement the shortener for `graph` command only in the PR.
