### ISSUE TITLE
Create `my state` command 

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#84]
This will get the location of the user and send the `/state_name` command results.

Refer: https://core.telegram.org/bots#location-and-number

**Comment by baljinderxd** [comment]
I implemented this and successfully received the location from the user.
But the received location object contains only longitude and latitude and I am not aware of how to get the name of the state using the coordinates only. 
I will try to find something for the same, and if you know something about it please do share 😬

**Comment by gurrrung** [comment]
1. Many free API services are available for that like [this](https://www.bigdatacloud.com/geocoding-apis/free-reverse-geocode-to-city-api?gclid=CjwKCAjwnef6BRAgEiwAgv8mQaxMWdn_aU69vR6FJXz5IhbQ81K4FUKuLtekPFlbWIGIGnQ0pjyF1xoCYm4QAvD_BwE).

2. Yes, we can take that.

**Comment by baljinderxd** [comment]
> 1. Many free API services are available for that like [this](https://www.bigdatacloud.com/geocoding-apis/free-reverse-geocode-to-city-api?gclid=CjwKCAjwnef6BRAgEiwAgv8mQaxMWdn_aU69vR6FJXz5IhbQ81K4FUKuLtekPFlbWIGIGnQ0pjyF1xoCYm4QAvD_BwE).

Oh, thanks I will use this 😄 
> 2. Yes, we can take that.

💯 💯
